// loccheck — keeps the string tables and the source in step.
//
//   swiftc -O Tools/loccheck/main.swift -o loccheck && ./loccheck .
//
// Scans every `L("key", "English")` call in Sources/, writes `Resources/en.lproj` from what it
// finds, and checks `Resources/zh-Hans.lproj` against it. Exits non-zero on any key that is used
// but not translated, any key translated but no longer used, and any key given two different
// English texts. Without this the tables drift silently: there is no Xcode project here to run
// genstrings, and a missing key shows up as English inside an otherwise Chinese panel — which is
// exactly the kind of defect that survives a demo and ships.

import Foundation

let root = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "."
let fm = FileManager.default

func swiftFiles(_ dir: String) -> [String] {
    guard let e = fm.enumerator(atPath: dir) else { return [] }
    return e.compactMap { $0 as? String }.filter { $0.hasSuffix(".swift") }.map { "\(dir)/\($0)" }.sorted()
}

// Key first, English second, tolerating a line break between the two arguments.
let call = try! NSRegularExpression(pattern: #"\bL\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)"#,
                                    options: [.dotMatchesLineSeparators])

var english: [String: String] = [:]
var whereUsed: [String: String] = [:]
var problems: [String] = []

for path in swiftFiles("\(root)/Sources") {
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { continue }
    for (n, rawLine) in text.components(separatedBy: "\n").enumerated() {
        // Doc comments in Loc.swift spell out example calls; they are not call sites.
        let t = rawLine.trimmingCharacters(in: .whitespaces)
        if t.hasPrefix("//") || t.hasPrefix("*") { continue }
        let r = NSRange(rawLine.startIndex..., in: rawLine)
        for m in call.matches(in: rawLine, range: r) {
            guard let k = Range(m.range(at: 1), in: rawLine), let v = Range(m.range(at: 2), in: rawLine) else { continue }
            let key = String(rawLine[k]), value = String(rawLine[v])
            let site = "\(path.replacingOccurrences(of: root + "/", with: "")):\(n + 1)"
            if let prior = english[key], prior != value {
                problems.append("· key '\(key)' has two English texts:\n    \(whereUsed[key] ?? "?")  \"\(prior)\"\n    \(site)  \"\(value)\"")
            }
            english[key] = value
            whereUsed[key] = site
        }
    }
}

/// Values arrive already carrying source-level escapes (\n, \"), which are exactly what a .strings
/// file wants, so they pass through untouched. Only a bare backslash would need doubling and none
/// is used.
func table(_ pairs: [(String, String)]) -> String {
    "// Generated by Tools/loccheck — do not edit. English lives at the call site in Sources/.\n"
        + pairs.sorted { $0.0 < $1.0 }.map { "\"\($0.0)\" = \"\($0.1)\";" }.joined(separator: "\n") + "\n"
}

func read(_ lproj: String) -> [String: String] {
    let p = "\(root)/Resources/\(lproj).lproj/Localizable.strings"
    guard let d = NSDictionary(contentsOfFile: p) as? [String: String] else { return [:] }
    return d
}

// en.lproj is generated, so it cannot be wrong.
let enDir = "\(root)/Resources/en.lproj"
try? fm.createDirectory(atPath: enDir, withIntermediateDirectories: true)
try! table(english.map { ($0.key, $0.value) }).write(toFile: "\(enDir)/Localizable.strings", atomically: true, encoding: .utf8)

let zh = read("zh-Hans")
let missing = english.keys.filter { zh[$0] == nil }.sorted()
let orphan = zh.keys.filter { english[$0] == nil }.sorted()

if !missing.isEmpty {
    problems.append("· \(missing.count) key(s) used in Sources but absent from zh-Hans.lproj:\n"
        + missing.map { "    \($0)  \(whereUsed[$0] ?? "")  \"\(english[$0]!)\"" }.joined(separator: "\n"))
}
if !orphan.isEmpty {
    problems.append("· \(orphan.count) key(s) in zh-Hans.lproj no longer used:\n"
        + orphan.map { "    \($0)  \"\(zh[$0]!)\"" }.joined(separator: "\n"))
}

if problems.isEmpty {
    print("✓ loccheck — \(english.count) keys, en + zh-Hans complete")
    exit(0)
}
print("✗ loccheck")
problems.forEach { print($0) }
exit(1)
