#!/usr/bin/env python3
"""Re-import the Paradise wing mark from 01 BRAND ASSETS into Sources/App/BrandMark.swift.

The wing must never be hand-edited (brand standard §2/§7). Regenerate the SVG with
`01 BRAND ASSETS/source/wing_gen.py`, then run this script to refresh the Swift path data.
"""
import re, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BRAND = os.path.abspath(os.path.join(ROOT, '..', '..', '01 BRAND ASSETS'))
SVG = os.environ.get('WING_SVG', os.path.join(BRAND, 'logo', 'symbol-amber.svg'))
OUT = os.path.join(ROOT, 'Sources', 'App', 'BrandMark.swift')

# The feather axis has to come from the generator, not be measured off the exported
# outline: width(0) is a small non-zero swell, so the polyline never passes through
# the root. Gauge gradients run along this axis, so an estimate here would show up as
# a fill that reads slightly wrong at every value.
sys.path.insert(0, os.path.join(BRAND, 'source'))
import wing_gen as W
_top = W.solve_top_angle()
_tips, _angs = W.spiral_tips(_top)
_roots = W.feather_roots()

src = open(SVG).read()
minx, miny, w, h = [float(x) for x in re.search(r'viewBox="([^"]+)"', src).group(1).split()]
paths = re.findall(r'<path d="([^"]+)"', src)
assert len(paths) == 5, f'expected 5 feathers, found {len(paths)}'

def points(d):
    out = []
    for tok in d.replace('M', '').replace('Z', '').split('L'):
        tok = tok.strip()
        if not tok:
            continue
        x, y = tok.split(',')
        out.append((float(x), float(y)))
    return out

# Normalise against the mark's own tight bounding box, not the SVG viewBox padding,
# so the exported aspect is the golden rectangle the generator solves for.
allpts = [pt for d in paths for pt in points(d)]
minx = min(x for x, _ in allpts); maxx = max(x for x, _ in allpts)
miny = min(y for _, y in allpts); maxy = max(y for _, y in allpts)
w, h = maxx - minx, maxy - miny

encoded = []
for d in paths:
    p = points(d)
    keep = p[::2]
    if keep[-1] != p[-1]:
        keep.append(p[-1])
    encoded.append(' '.join(f'{round((x - minx) / w, 4):g},{round((y - miny) / h, 4):g}' for x, y in keep))

def norm(pt):
    return (pt[0] - minx) / w, (pt[1] - miny) / h

axes = []
for r, t in zip(_roots, _tips):
    (rx, ry), (tx, ty) = norm(r), norm(t)
    axes.append(f'{rx:.5f},{ry:.5f},{tx:.5f},{ty:.5f}')

body = ',\n'.join(f'        "{e}"' for e in encoded)
axisbody = ',\n'.join(f'        "{a}"' for a in axes)
open(OUT, 'w').write(f'''import AppKit

/// The Paradise Production wing mark — five feathers on a golden-ratio armature, generated by
/// `01 BRAND ASSETS/source/wing_gen.py`. Geometry is imported, never hand-edited: refresh it with
/// `Tools/import_wing.py` after regenerating the SVG (brand standard sections 2 and 7).
///
/// Two forms. `path(in:)` merges the five feathers into one shape — that is the identity mark, and
/// the only form permitted outside the app (icon, DMG, README). `paths(in:)` and `axis(_:in:)`
/// expose the feathers individually so the mark can act as a live gauge inside the app, which
/// standard §7.1 allows and nothing else does.
enum BrandMark {{
    /// width / height of the mark's bounding box (a golden rectangle).
    static let aspect: CGFloat = {w / h:.6f}
    /// Feathers, root to tip of the fan. Fixed at five by the standard.
    static let count = {len(encoded)}

    private static let feathers: [String] = [
{body}
    ]

    /// `rootX,rootY,tipX,tipY` per feather, in the same normalised box as `feathers`, taken from
    /// the generator's armature. It cannot be read back off the outline: the feather tapers to a
    /// small but non-zero width at the root, so the polyline never passes through it.
    private static let axes: [String] = [
{axisbody}
    ]

    private static let merged = NSCache<NSString, NSBezierPath>()
    private static let split = NSCache<NSString, NSArray>()

    /// The mark's own golden box inside `rect`, aspect preserved and centred.
    static func box(in rect: CGRect) -> CGRect {{
        let fit = min(rect.width / aspect, rect.height)
        return CGRect(x: rect.midX - fit * aspect / 2, y: rect.midY - fit / 2, width: fit * aspect, height: fit)
    }}

    // SVG y grows downward, AppKit y grows upward.
    private static func point(_ nx: Double, _ ny: Double, in box: CGRect) -> CGPoint {{
        CGPoint(x: box.minX + CGFloat(nx) * box.width, y: box.maxY - CGFloat(ny) * box.height)
    }}

    private static func outline(_ feather: String, in box: CGRect) -> NSBezierPath {{
        let path = NSBezierPath()
        var first = true
        for pair in feather.split(separator: " ") {{
            let xy = pair.split(separator: ",")
            guard xy.count == 2, let nx = Double(xy[0]), let ny = Double(xy[1]) else {{ continue }}
            let p = point(nx, ny, in: box)
            if first {{ path.move(to: p); first = false }} else {{ path.line(to: p) }}
        }}
        path.close()
        return path
    }}

    /// One path per feather, innermost first. Use this to colour or clip feathers independently.
    static func paths(in rect: CGRect) -> [NSBezierPath] {{
        let key = "\\(rect)" as NSString
        if let hit = split.object(forKey: key) as? [NSBezierPath] {{ return hit }}
        let box = box(in: rect)
        let out = feathers.map {{ outline($0, in: box) }}
        split.setObject(out as NSArray, forKey: key)
        return out
    }}

    /// The whole mark as a single path — the identity form.
    static func path(in rect: CGRect) -> NSBezierPath {{
        let key = "\\(rect)" as NSString
        if let hit = merged.object(forKey: key) {{ return hit }}
        let path = NSBezierPath()
        for sub in paths(in: rect) {{ path.append(sub) }}
        merged.setObject(path, forKey: key)
        return path
    }}

    /// Feather `k`'s centreline endpoints. A gradient drawn between these runs along the feather
    /// rather than across it, so its position reads as a distance travelled out the feather.
    static func axis(_ k: Int, in rect: CGRect) -> (root: CGPoint, tip: CGPoint) {{
        let box = box(in: rect)
        let v = axes[k].split(separator: ",").compactMap {{ Double($0) }}
        guard v.count == 4 else {{ return (box.origin, box.origin) }}
        return (point(v[0], v[1], in: box), point(v[2], v[3], in: box))
    }}

    static func draw(in rect: CGRect, color: NSColor) {{
        color.setFill()
        path(in: rect).fill()
    }}
}}
''')
print(f'wrote {OUT} — {len(encoded)} feathers, aspect {w / h:.6f}, {sum(len(e) for e in encoded)} chars')
print('axes  ' + ' | '.join(axes))
