#!/usr/bin/env python3
"""Re-import the Paradise wing mark from 01 BRAND ASSETS into Sources/App/BrandMark.swift.

The wing must never be hand-edited (brand standard §2/§7). Regenerate the SVG with
`01 BRAND ASSETS/source/wing_gen.py`, then run this script to refresh the Swift path data.
"""
import re, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SVG = os.environ.get('WING_SVG', os.path.join(ROOT, '..', '..', '01 BRAND ASSETS', 'logo', 'symbol-amber.svg'))
OUT = os.path.join(ROOT, 'Sources', 'App', 'BrandMark.swift')

src = open(SVG).read()
minx, miny, w, h = [float(x) for x in re.search(r'viewBox="([^"]+)"', src).group(1).split()]
paths = re.findall(r'<path d="([^"]+)"', src)
assert len(paths) == 5, f'expected 5 feathers, found {len(paths)}'

def points(d):
    out = []
    for tok in d.replace('M', '').replace('Z', '').split('L'):
        tok = tok.strip()
        if not tok:
            continue
        x, y = tok.split(',')
        out.append((float(x), float(y)))
    return out

# Normalise against the mark's own tight bounding box, not the SVG viewBox padding,
# so the exported aspect is the golden rectangle the generator solves for.
allpts = [pt for d in paths for pt in points(d)]
minx = min(x for x, _ in allpts); maxx = max(x for x, _ in allpts)
miny = min(y for _, y in allpts); maxy = max(y for _, y in allpts)
w, h = maxx - minx, maxy - miny

encoded = []
for d in paths:
    p = points(d)
    keep = p[::2]
    if keep[-1] != p[-1]:
        keep.append(p[-1])
    encoded.append(' '.join(f'{round((x - minx) / w, 4):g},{round((y - miny) / h, 4):g}' for x, y in keep))

body = ',\n'.join(f'        "{e}"' for e in encoded)
open(OUT, 'w').write(f'''import AppKit

/// The Paradise Production wing mark — five feathers on a golden-ratio armature, generated by
/// `01 BRAND ASSETS/source/wing_gen.py`. Geometry is imported, never hand-edited: refresh it with
/// `Tools/import_wing.py` after regenerating the SVG (brand standard sections 2 and 7).
enum BrandMark {{
    /// width / height of the mark's bounding box (a golden rectangle).
    static let aspect: CGFloat = {w / h:.6f}

    private static let feathers: [String] = [
{body}
    ]

    private static let cache = NSCache<NSString, NSBezierPath>()

    /// The wing fitted inside `rect`, aspect preserved and centred.
    static func path(in rect: CGRect) -> NSBezierPath {{
        let key = "\\(rect)" as NSString
        if let hit = cache.object(forKey: key) {{ return hit }}
        let fit = min(rect.width / aspect, rect.height)
        let box = CGRect(x: rect.midX - fit * aspect / 2, y: rect.midY - fit / 2, width: fit * aspect, height: fit)
        let path = NSBezierPath()
        for feather in feathers {{
            var first = true
            for pair in feather.split(separator: " ") {{
                let xy = pair.split(separator: ",")
                guard xy.count == 2, let nx = Double(xy[0]), let ny = Double(xy[1]) else {{ continue }}
                // SVG y grows downward, AppKit y grows upward.
                let p = CGPoint(x: box.minX + CGFloat(nx) * box.width, y: box.maxY - CGFloat(ny) * box.height)
                if first {{ path.move(to: p); first = false }} else {{ path.line(to: p) }}
            }}
            path.close()
        }}
        cache.setObject(path, forKey: key)
        return path
    }}

    static func draw(in rect: CGRect, color: NSColor) {{
        color.setFill()
        path(in: rect).fill()
    }}
}}
''')
print(f'wrote {OUT} — {len(encoded)} feathers, aspect {w / h:.6f}, {sum(len(e) for e in encoded)} chars')
